*$SETGLOBAL input SAM_SSB_NACE_2018_GasChem
*$SETGLOBAL input SAM_SSB_2020
$SETGLOBAL input SAM_SSB_2019
$SETGLOBAL RegKey 1
$SETGLOBAL IndKey 1
$SETGLOBAL ProdKey 1
$SETGLOBAL FinKey 1




